name = "nodeui-collaboration-do"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[durable_objects.bindings]]
name = "COLLABORATION_ROOMS"
class_name = "CollaborationRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CollaborationRoom"]
